### ISSUE TITLE
time series data not included

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL-SIIP/PyPSA2PowerSystems.jl#2]

**Comment by claytonpbarrows** [comment]
@pz-max can you point me to a PyPSA netcdf file with multiple time points? It doesn't have to be for the RTS, I just need an example of the structure.

**Comment by pz-max** [comment]
To view elec_s_70_ec_lv1.05_Co2L0.0-24H.nc, sign in<https://uoe-my.sharepoint.com/personal/s1827105_ed_ac_uk/_layouts/15/acceptinvite.aspx?invitation=%7B2F4E8695%2D05EF%2D46D3%2D848B%2D10176115B9AE%7D&listId=6f16a83e%2D294d%2D410f%2Dbe7d%2Da64904177314&itemId=aadd576a%2D8773%2D43b0%2D9445%2Dcccfe4f058a7> or create an account.
The University of Edinburgh is a charitable body, registered in Scotland, with registration number SC005336. Is e buidheann carthannais a th' ann an Oilthigh Dh?n ?ideann, cl?raichte an Alba, ?ireamh cl?raidh SC005336.

**Comment by pz-max** [comment]
PARZEN Maximilian has shared a OneDrive for Business file with you. To view it, click the link below.
<https://uoe-my.sharepoint.com/personal/s1827105_ed_ac_uk/Documents/Attachments/elec_s_70_ec_lv1.05_Co2L0.0-24H.nc>
[https://r1.res.office365.com/owa/prem/images/dc-generic_20.png]<https://uoe-my.sharepoint.com/personal/s1827105_ed_ac_uk/Documents/Attachments/elec_s_70_ec_lv1.05_Co2L0.0-24H.nc>
elec_s_70_ec_lv1.05_Co2L0.0-24H.nc<https://uoe-my.sharepoint.com/personal/s1827105_ed_ac_uk/Documents/Attachments/elec_s_70_ec_lv1.05_Co2L0.0-24H.nc>

Hi Clayton, attached a .nc file example with multiple time points. Let me know if you need help reading it.
The documentation and examples of PyPSA helps a lot https://pypsa.readthedocs.io/en/latest/index.html

________________________________

**Comment by claytonpbarrows** [comment]
7e6be907029af286e6bfa4173e944f159ccf5b6c closes
